name       : cockatrice
version    : 2.3.17
release    : 7
source     :
    - https://github.com/Cockatrice/Cockatrice/archive/2017-05-05-Release-2.3.17.tar.gz : 95f78db3c2f4f93e2b007b92687cb1655ce5d6b23d72aeb85fc043f60748701e
license    :
    - GPL-2.0
component  : games.card
summary    : A cross-platform virtual tabletop for multiplayer card games
description: |
    Cockatrice is an open-source multiplatform software for playing card games, such as Magic: The Gathering, over a network. It is fully client-server based to prevent any kind of cheating, though it supports single-player games without a network interface as well. Both client and server are written in Qt, supporting both Qt4 and Qt5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(protobuf)
    - pkgconfig(gl)
rundeps    :
    - wget
setup      : |
    %cmake -DWITH_SERVER=1
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/cockatrice/themes/Default/.gitignore
