name       : cockatrice
version    : 2.7.0
release    : 11
source     :
    - https://github.com/Cockatrice/Cockatrice/archive/2019-03-04-Release-2.7.0.tar.gz : b46702d4f508c45039b11ffb6382ba530a6ebcf5d7461de567d356c47d245ac3
license    : GPL-2.0-or-later
component  : games.card
summary    : A cross-platform virtual tabletop for multiplayer card games
description: |
    Cockatrice is an open-source multiplatform software for playing card games, such as Magic: The Gathering, over a network. It is fully client-server based to prevent any kind of cheating, though it supports single-player games without a network interface as well. Both client and server are written in Qt, supporting both Qt4 and Qt5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(protobuf)
rundeps    :
    - wget
setup      : |
    %cmake -DWITH_SERVER=1
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/cockatrice/themes/Default/.gitignore
